export type Currency = {
  name: string
  ticker: string
  displayTicker: string
  digitalCurrency: boolean
  erc20Token: boolean
  symbol: string
  numberOfDecimalPlaces: number
  displayDecimalPlaces: number
  commonName: string
  commonTicker: string
  network: string
  shortSymbol: string
  flag?: string
}

export type ChainItem = {
  name: string
  symbol: string
}
//  Denmark (DK), Dominican Republic (DO), Estonia (EE), Finland (FI), France (FR), France (FR), Germany (DE), Great Britain (GB), Greece (GR), Hong Kong (HK), Iceland (IS), India (IN), Indonesia (ID), Ireland (IE), Israel (IL), Italy (IT), Japan (JP), Laos, Latvia (LV), Lithuania (LT), Luxembourg (LU), Malaysia (MY), Mexico (MX), Nepal (NP), New Zealand (NZ), Norway (NO), Paraguay (PY), Peru (PE), Philippines (PH), Poland (PL), Portugal (PT) ,Singapore (SG), Slovakia (SK), Slovenia (SI), South Africa (ZA), South Korea (KR), Spain (ES), Sweden (SE), Switzerland (CH), Tanzania (TZ), Thailand (TH), The Netherlands (NL), Turkey (TR), Vietnam (VN)
export const WYER_CONFIG = {
  chains: [
    {
      name: 'Ethereum',
      symbol: 'ethereum'
    },
    {
      name: 'Bitcoin',
      symbol: 'bitcoin'
    },
    {
      name: 'Loopring',
      symbol: 'loopring'
    },
    {
      name: 'Stellar',
      symbol: 'stellar'
    },
    {
      name: 'Avalanche',
      symbol: 'avalanche',
      otherNames: ['Avalanche C-Chain', 'Avalanche X-Chain']
    },
    {
      name: 'Polygon',
      symbol: 'polygon'
    },
    {
      name: 'Algorand',
      symbol: 'algorand'
    },
    {
      name: 'Flow',
      symbol: 'flow'
    }
  ],
  countries: [
    {
      name: 'Czech Republic',
      symbol: 'CZ'
    },
    {
      name: 'Cyprus',
      symbol: 'CR'
    },
    {
      name: 'Costa Rica',
      symbol: 'CR'
    },
    {
      name: 'Colombia',
      symbol: 'CO'
    },
    {
      name: 'Chile',
      symbol: 'CL'
    },
    {
      name: 'Algeria',
      symbol: 'DZ'
    },
    {
      name: 'Argentina',
      symbol: 'AR'
    },
    {
      name: 'Australia',
      symbol: 'AU'
    },
    {
      name: 'Austria',
      symbol: 'AT'
    },
    {
      name: 'Belgium',
      symbol: 'BE'
    },
    {
      name: 'Bolivia',
      symbol: 'BO'
    },
    {
      name: 'Canada',
      symbol: 'AU'
    }
  ],
  currencies: [
    {
      name: 'Aave',
      ticker: 'AAVE',
      displayTicker: 'AAVE',
      digitalCurrency: true,
      erc20Token: true,
      symbol: '',
      numberOfDecimalPlaces: 18,
      displayDecimalPlaces: 8,
      commonName: 'Aave',
      commonTicker: 'AAVE',
      network: 'Ethereum',
      shortSymbol: ''
    },
    {
      name: 'Algorand',
      ticker: 'ALGO',
      displayTicker: 'ALGO',
      digitalCurrency: true,
      erc20Token: false,
      symbol: '',
      numberOfDecimalPlaces: 18,
      displayDecimalPlaces: 8,
      commonName: 'Algorand',
      commonTicker: 'ALGO',
      network: 'Algorand',
      shortSymbol: ''
    },
    {
      name: 'Argentine Peso',
      ticker: 'ARS',
      displayTicker: 'ARS',
      digitalCurrency: false,
      erc20Token: false,
      symbol: '$',
      numberOfDecimalPlaces: 2,
      displayDecimalPlaces: 2,
      commonName: 'Argentine Peso',
      commonTicker: 'ARS',
      network: 'None',
      shortSymbol: '$'
    },
    {
      name: 'Australian Dollar',
      ticker: 'AUD',
      displayTicker: 'AUD',
      digitalCurrency: false,
      erc20Token: false,
      symbol: 'A$',
      numberOfDecimalPlaces: 2,
      displayDecimalPlaces: 2,
      commonName: 'Australian Dollar',
      commonTicker: 'AUD',
      network: 'None',
      shortSymbol: '$'
    },
    {
      name: 'aUSDC',
      ticker: 'AUSDC',
      displayTicker: 'Algorand USDC',
      digitalCurrency: true,
      erc20Token: true,
      symbol: '$',
      numberOfDecimalPlaces: 6,
      displayDecimalPlaces: 6,
      commonName: 'USD Coin',
      commonTicker: 'USDC',
      network: 'Algorand',
      shortSymbol: '$'
    },
    {
      name: 'aUSDT',
      ticker: 'AUSDT',
      displayTicker: 'Algorand USDT',
      digitalCurrency: true,
      erc20Token: true,
      symbol: '₮',
      numberOfDecimalPlaces: 6,
      displayDecimalPlaces: 6,
      commonName: 'Tether',
      commonTicker: 'USDT',
      network: 'Algorand',
      shortSymbol: '₮'
    },
    {
      name: 'Avalanche',
      ticker: 'AVAX',
      displayTicker: 'AVAX',
      digitalCurrency: true,
      erc20Token: false,
      symbol: '',
      numberOfDecimalPlaces: 18,
      displayDecimalPlaces: 8,
      commonName: 'Avalanche',
      commonTicker: 'AVAX',
      network: 'Avalanche X-Chain',
      shortSymbol: ''
    },
    {
      name: 'Avax C-Chain',
      ticker: 'AVAXC',
      displayTicker: 'AVAXC',
      digitalCurrency: true,
      erc20Token: false,
      symbol: '',
      numberOfDecimalPlaces: 18,
      displayDecimalPlaces: 8,
      commonName: 'Avalanche',
      commonTicker: 'AVAX',
      network: 'Avalanche C-Chain',
      shortSymbol: ''
    },
    {
      name: 'AVAXC USDC',
      ticker: 'AVAXCUSDC',
      displayTicker: 'Avax C-Chain USDC',
      digitalCurrency: true,
      erc20Token: true,
      symbol: '$',
      numberOfDecimalPlaces: 6,
      displayDecimalPlaces: 6,
      commonName: 'USD Coin',
      commonTicker: 'USDC',
      network: 'Avalanche C-Chain',
      shortSymbol: '$'
    },
    {
      name: 'Basic Attention Token',
      ticker: 'BAT',
      displayTicker: 'BAT',
      digitalCurrency: true,
      erc20Token: true,
      symbol: '',
      numberOfDecimalPlaces: 18,
      displayDecimalPlaces: 8,
      commonName: 'Basic Attention Token',
      commonTicker: 'BAT',
      network: 'Ethereum',
      shortSymbol: ''
    },
    {
      name: 'Brazilian Real',
      ticker: 'BRL',
      displayTicker: 'BRL',
      digitalCurrency: false,
      erc20Token: false,
      symbol: 'R$',
      numberOfDecimalPlaces: 2,
      displayDecimalPlaces: 2,
      commonName: 'Brazilian Real',
      commonTicker: 'BRL',
      network: 'None',
      shortSymbol: '$'
    },
    {
      name: 'bitcoin',
      ticker: 'BTC',
      displayTicker: 'BTC',
      digitalCurrency: true,
      erc20Token: false,
      symbol: '฿',
      numberOfDecimalPlaces: 8,
      displayDecimalPlaces: 8,
      commonName: 'Bitcoin',
      commonTicker: 'BTC',
      network: 'Bitcoin',
      shortSymbol: '฿'
    },
    {
      name: 'Binance USD',
      ticker: 'BUSD',
      displayTicker: 'BUSD',
      digitalCurrency: true,
      erc20Token: true,
      symbol: '',
      numberOfDecimalPlaces: 18,
      displayDecimalPlaces: 8,
      commonName: 'Binance USD',
      commonTicker: 'BUSD',
      network: 'Ethereum',
      shortSymbol: ''
    },
    {
      name: 'Canadian Dollar',
      ticker: 'CAD',
      displayTicker: 'CAD',
      digitalCurrency: false,
      erc20Token: false,
      symbol: 'C$',
      numberOfDecimalPlaces: 2,
      displayDecimalPlaces: 2,
      commonName: 'Canadian Dollar',
      commonTicker: 'CAD',
      network: 'None',
      shortSymbol: '$'
    },
    {
      name: 'Swiss Franc',
      ticker: 'CHF',
      displayTicker: 'CHF',
      digitalCurrency: false,
      erc20Token: false,
      symbol: 'CHF',
      numberOfDecimalPlaces: 2,
      displayDecimalPlaces: 2,
      commonName: 'Swiss Franc',
      commonTicker: 'CHF',
      network: 'None',
      shortSymbol: ''
    },
    {
      name: 'Chilean Peso',
      ticker: 'CLP',
      displayTicker: 'CLP',
      digitalCurrency: false,
      erc20Token: false,
      symbol: '$',
      numberOfDecimalPlaces: 2,
      displayDecimalPlaces: 2,
      commonName: 'Chilean Peso',
      commonTicker: 'CLP',
      network: 'None',
      shortSymbol: '$'
    },
    {
      name: 'Chinese Yuan',
      ticker: 'CNY',
      displayTicker: 'CNY',
      digitalCurrency: false,
      erc20Token: false,
      symbol: 'CN¥',
      numberOfDecimalPlaces: 2,
      displayDecimalPlaces: 2,
      commonName: 'Chinese Yuan',
      commonTicker: 'CNY',
      network: 'None',
      shortSymbol: '¥'
    },
    {
      name: 'Compound',
      ticker: 'COMP',
      displayTicker: 'COMP',
      digitalCurrency: true,
      erc20Token: true,
      symbol: '',
      numberOfDecimalPlaces: 18,
      displayDecimalPlaces: 8,
      commonName: 'Compound',
      commonTicker: 'COMP',
      network: 'Ethereum',
      shortSymbol: ''
    },
    {
      name: 'Colombian Peso',
      ticker: 'COP',
      displayTicker: 'COP',
      digitalCurrency: false,
      erc20Token: false,
      symbol: '$',
      numberOfDecimalPlaces: 2,
      displayDecimalPlaces: 2,
      commonName: 'Colombian Peso',
      commonTicker: 'COP',
      network: 'None',
      shortSymbol: '$'
    },
    {
      name: 'Curve',
      ticker: 'CRV',
      displayTicker: 'CRV',
      digitalCurrency: true,
      erc20Token: true,
      symbol: '',
      numberOfDecimalPlaces: 18,
      displayDecimalPlaces: 8,
      commonName: 'Curve',
      commonTicker: 'CRV',
      network: 'Ethereum',
      shortSymbol: ''
    },
    {
      name: 'Czech Koruna',
      ticker: 'CZK',
      displayTicker: 'CZK',
      digitalCurrency: false,
      erc20Token: false,
      symbol: 'Kč',
      numberOfDecimalPlaces: 2,
      displayDecimalPlaces: 2,
      commonName: 'Czech Koruna',
      commonTicker: 'CZK',
      network: 'None',
      shortSymbol: 'č'
    },
    {
      name: 'dai',
      ticker: 'DAI',
      displayTicker: 'DAI',
      digitalCurrency: true,
      erc20Token: true,
      symbol: '',
      numberOfDecimalPlaces: 18,
      displayDecimalPlaces: 8,
      commonName: 'Dai',
      commonTicker: 'DAI',
      network: 'Ethereum',
      shortSymbol: ''
    },
    {
      name: 'Danish Krone',
      ticker: 'DKK',
      displayTicker: 'DKK',
      digitalCurrency: false,
      erc20Token: false,
      symbol: 'kr',
      numberOfDecimalPlaces: 2,
      displayDecimalPlaces: 2,
      commonName: 'Danish Krone',
      commonTicker: 'DKK',
      network: 'None',
      shortSymbol: ''
    },
    {
      name: 'EBTCQ',
      ticker: 'EBTCQ',
      displayTicker: 'Ember BTC Quant',
      digitalCurrency: true,
      erc20Token: true,
      symbol: '',
      numberOfDecimalPlaces: 18,
      displayDecimalPlaces: 6,
      commonName: 'Ember BTC Quant',
      commonTicker: 'EBTCQ',
      network: 'Ethereum',
      shortSymbol: ''
    },
    {
      name: 'Ember Defi Index',
      ticker: 'EDI',
      displayTicker: 'EDI',
      digitalCurrency: true,
      erc20Token: true,
      symbol: '',
      numberOfDecimalPlaces: 18,
      displayDecimalPlaces: 6,
      commonName: 'Ember Defi Index',
      commonTicker: 'EDI',
      network: 'Ethereum',
      shortSymbol: ''
    },
    {
      name: 'Ethereum Flux',
      ticker: 'EFLUX',
      displayTicker: 'Ethereum Flux',
      digitalCurrency: true,
      erc20Token: true,
      symbol: '',
      numberOfDecimalPlaces: 8,
      displayDecimalPlaces: 8,
      commonName: 'Flux',
      commonTicker: 'FLUX',
      network: 'Ethereum',
      shortSymbol: ''
    },
    {
      name: 'EGBTC',
      ticker: 'EGBTC',
      displayTicker: 'E-Gift BTC',
      digitalCurrency: true,
      erc20Token: true,
      symbol: '',
      numberOfDecimalPlaces: 18,
      displayDecimalPlaces: 6,
      commonName: 'E-Gift BTC',
      commonTicker: 'EGBTC',
      network: 'Ethereum',
      shortSymbol: ''
    },
    {
      name: 'ethereum',
      ticker: 'ETH',
      displayTicker: 'ETH',
      digitalCurrency: true,
      erc20Token: false,
      symbol: 'Ξ',
      numberOfDecimalPlaces: 18,
      displayDecimalPlaces: 8,
      commonName: 'Ethereum',
      commonTicker: 'ETH',
      network: 'Ethereum',
      shortSymbol: 'Ξ'
    },
    {
      name: 'Euro',
      ticker: 'EUR',
      displayTicker: 'EUR',
      digitalCurrency: false,
      erc20Token: false,
      symbol: '€',
      numberOfDecimalPlaces: 2,
      displayDecimalPlaces: 2,
      commonName: 'Euro',
      commonTicker: 'EUR',
      network: 'None',
      shortSymbol: '€'
    },
    {
      name: 'FUSD',
      ticker: 'FUSD',
      displayTicker: 'Flow USD',
      digitalCurrency: true,
      erc20Token: true,
      symbol: '$',
      numberOfDecimalPlaces: 8,
      displayDecimalPlaces: 8,
      commonName: 'Flow USD',
      commonTicker: 'FUSD',
      network: 'Flow',
      shortSymbol: '$'
    },
    {
      name: 'Pound Sterling',
      ticker: 'GBP',
      displayTicker: 'GBP',
      digitalCurrency: false,
      erc20Token: false,
      symbol: '£',
      numberOfDecimalPlaces: 2,
      displayDecimalPlaces: 2,
      commonName: 'Pound Sterling',
      commonTicker: 'GBP',
      network: 'None',
      shortSymbol: '£'
    },
    {
      name: 'Gemini Dollar',
      ticker: 'GUSD',
      displayTicker: 'GUSD',
      digitalCurrency: true,
      erc20Token: true,
      symbol: '',
      numberOfDecimalPlaces: 2,
      displayDecimalPlaces: 2,
      commonName: 'Gemini Dollar',
      commonTicker: 'GUSD',
      network: 'Ethereum',
      shortSymbol: ''
    },
    {
      name: 'Hong Kong Dollar',
      ticker: 'HKD',
      displayTicker: 'HKD',
      digitalCurrency: false,
      erc20Token: false,
      symbol: 'HK$',
      numberOfDecimalPlaces: 2,
      displayDecimalPlaces: 2,
      commonName: 'Hong Kong Dollar',
      commonTicker: 'HKD',
      network: 'None',
      shortSymbol: '$'
    },
    {
      name: 'Huobi Dollar',
      ticker: 'HUSD',
      displayTicker: 'HUSD',
      digitalCurrency: true,
      erc20Token: true,
      symbol: '',
      numberOfDecimalPlaces: 8,
      displayDecimalPlaces: 8,
      commonName: 'Huobi Dollar',
      commonTicker: 'HUSD',
      network: 'Ethereum',
      shortSymbol: ''
    },
    {
      name: 'Israeli New Shekel',
      ticker: 'ILS',
      displayTicker: 'ILS',
      digitalCurrency: false,
      erc20Token: false,
      symbol: '₪',
      numberOfDecimalPlaces: 2,
      displayDecimalPlaces: 2,
      commonName: 'Israeli New Shekel',
      commonTicker: 'ILS',
      network: 'None',
      shortSymbol: '₪'
    },
    {
      name: 'Indian Rupee',
      ticker: 'INR',
      displayTicker: 'INR',
      digitalCurrency: false,
      erc20Token: false,
      symbol: '₹',
      numberOfDecimalPlaces: 2,
      displayDecimalPlaces: 2,
      commonName: 'Indian Rupee',
      commonTicker: 'INR',
      network: 'None',
      shortSymbol: '₹'
    },
    {
      name: 'Icelandic Króna',
      ticker: 'ISK',
      displayTicker: 'ISK',
      digitalCurrency: false,
      erc20Token: false,
      symbol: 'kr',
      numberOfDecimalPlaces: 2,
      displayDecimalPlaces: 2,
      commonName: 'Icelandic Króna',
      commonTicker: 'ISK',
      network: 'None',
      shortSymbol: ''
    },
    {
      name: 'Japanese Yen',
      ticker: 'JPY',
      displayTicker: 'JPY',
      digitalCurrency: false,
      erc20Token: false,
      symbol: 'JP¥',
      numberOfDecimalPlaces: 0,
      displayDecimalPlaces: 0,
      commonName: 'Japanese Yen',
      commonTicker: 'JPY',
      network: 'None',
      shortSymbol: '¥'
    },
    {
      name: 'South Korean Won',
      ticker: 'KRW',
      displayTicker: 'KRW',
      digitalCurrency: false,
      erc20Token: false,
      symbol: '₩',
      numberOfDecimalPlaces: 0,
      displayDecimalPlaces: 0,
      commonName: 'South Korean Won',
      commonTicker: 'KRW',
      network: 'None',
      shortSymbol: '₩'
    },
    {
      name: 'LETH',
      ticker: 'LETH',
      displayTicker: 'Loopring Ethereum',
      digitalCurrency: true,
      erc20Token: true,
      symbol: 'Ξ',
      numberOfDecimalPlaces: 18,
      displayDecimalPlaces: 8,
      commonName: 'Ethereum',
      commonTicker: 'ETH',
      network: 'Loopring',
      shortSymbol: 'Ξ'
    },
    {
      name: 'Chainlink',
      ticker: 'LINK',
      displayTicker: 'LINK',
      digitalCurrency: true,
      erc20Token: true,
      symbol: '',
      numberOfDecimalPlaces: 18,
      displayDecimalPlaces: 8,
      commonName: 'Chainlink',
      commonTicker: 'LINK',
      network: 'Ethereum',
      shortSymbol: ''
    },
    {
      name: 'LUSDC',
      ticker: 'LUSDC',
      displayTicker: 'Loopring USDC',
      digitalCurrency: true,
      erc20Token: true,
      symbol: '$',
      numberOfDecimalPlaces: 6,
      displayDecimalPlaces: 6,
      commonName: 'USD Coin',
      commonTicker: 'USDC',
      network: 'Loopring',
      shortSymbol: '$'
    },
    {
      name: 'Matic',
      ticker: 'MATIC',
      displayTicker: 'MATIC',
      digitalCurrency: true,
      erc20Token: false,
      symbol: '',
      numberOfDecimalPlaces: 18,
      displayDecimalPlaces: 8,
      commonName: 'Matic',
      commonTicker: 'MATIC',
      network: 'Polygon',
      shortSymbol: ''
    },
    {
      name: 'Maker',
      ticker: 'MKR',
      displayTicker: 'MKR',
      digitalCurrency: true,
      erc20Token: true,
      symbol: '',
      numberOfDecimalPlaces: 18,
      displayDecimalPlaces: 8,
      commonName: 'Maker',
      commonTicker: 'MKR',
      network: 'Ethereum',
      shortSymbol: ''
    },
    {
      name: 'mUSDC',
      ticker: 'MUSDC',
      displayTicker: 'Matic USDC',
      digitalCurrency: true,
      erc20Token: true,
      symbol: '$',
      numberOfDecimalPlaces: 6,
      displayDecimalPlaces: 6,
      commonName: 'USD Coin',
      commonTicker: 'USDC',
      network: 'Polygon',
      shortSymbol: '$'
    },
    {
      name: 'Mexican Peso',
      ticker: 'MXN',
      displayTicker: 'MXN',
      digitalCurrency: false,
      erc20Token: false,
      symbol: 'MX$',
      numberOfDecimalPlaces: 2,
      displayDecimalPlaces: 2,
      commonName: 'Mexican Peso',
      commonTicker: 'MXN',
      network: 'None',
      shortSymbol: '$'
    },
    {
      name: 'Malaysian Ringgit',
      ticker: 'MYR',
      displayTicker: 'MYR',
      digitalCurrency: false,
      erc20Token: false,
      symbol: 'RM',
      numberOfDecimalPlaces: 2,
      displayDecimalPlaces: 2,
      commonName: 'Malaysian Ringgit',
      commonTicker: 'MYR',
      network: 'None',
      shortSymbol: ''
    },
    {
      name: 'Norwegian Krone',
      ticker: 'NOK',
      displayTicker: 'NOK',
      digitalCurrency: false,
      erc20Token: false,
      symbol: 'kr',
      numberOfDecimalPlaces: 2,
      displayDecimalPlaces: 2,
      commonName: 'Norwegian Krone',
      commonTicker: 'NOK',
      network: 'None',
      shortSymbol: ''
    },
    {
      name: 'New Zealand Dollar',
      ticker: 'NZD',
      displayTicker: 'NZD',
      digitalCurrency: false,
      erc20Token: false,
      symbol: 'NZ$',
      numberOfDecimalPlaces: 2,
      displayDecimalPlaces: 2,
      commonName: 'New Zealand Dollar',
      commonTicker: 'NZD',
      network: 'None',
      shortSymbol: '$'
    },
    {
      name: 'Paxos Standard',
      ticker: 'PAX',
      displayTicker: 'PAX',
      digitalCurrency: true,
      erc20Token: true,
      symbol: '',
      numberOfDecimalPlaces: 18,
      displayDecimalPlaces: 8,
      commonName: 'Paxos Standard',
      commonTicker: 'PAX',
      network: 'Ethereum',
      shortSymbol: ''
    },
    {
      name: 'pDAI',
      ticker: 'PDAI',
      displayTicker: 'Palm DAI',
      digitalCurrency: true,
      erc20Token: true,
      symbol: '',
      numberOfDecimalPlaces: 18,
      displayDecimalPlaces: 8,
      commonName: 'Dai',
      commonTicker: 'DAI',
      network: 'Palm',
      shortSymbol: ''
    },
    {
      name: 'Philippine Peso',
      ticker: 'PHP',
      displayTicker: 'PHP',
      digitalCurrency: false,
      erc20Token: false,
      symbol: '₱',
      numberOfDecimalPlaces: 2,
      displayDecimalPlaces: 2,
      commonName: 'Philippine Peso',
      commonTicker: 'PHP',
      network: 'None',
      shortSymbol: '₱'
    },
    {
      name: 'Polish Złoty',
      ticker: 'PLN',
      displayTicker: 'PLN',
      digitalCurrency: false,
      erc20Token: false,
      symbol: 'zł',
      numberOfDecimalPlaces: 2,
      displayDecimalPlaces: 2,
      commonName: 'Polish Złoty',
      commonTicker: 'PLN',
      network: 'None',
      shortSymbol: 'ł'
    },
    {
      name: 'RAI',
      ticker: 'RAI',
      displayTicker: 'RAI',
      digitalCurrency: true,
      erc20Token: true,
      symbol: '',
      numberOfDecimalPlaces: 18,
      displayDecimalPlaces: 8,
      commonName: 'Rai Reflex Index',
      commonTicker: 'RAI',
      network: 'Ethereum',
      shortSymbol: ''
    },
    {
      name: 'Swedish Krona',
      ticker: 'SEK',
      displayTicker: 'SEK',
      digitalCurrency: false,
      erc20Token: false,
      symbol: 'kr',
      numberOfDecimalPlaces: 2,
      displayDecimalPlaces: 2,
      commonName: 'Swedish Krona',
      commonTicker: 'SEK',
      network: 'None',
      shortSymbol: ''
    },
    {
      name: 'Singapore Dollar',
      ticker: 'SGD',
      displayTicker: 'SGD',
      digitalCurrency: false,
      erc20Token: false,
      symbol: 'S$',
      numberOfDecimalPlaces: 2,
      displayDecimalPlaces: 2,
      commonName: 'Singapore Dollar',
      commonTicker: 'SGD',
      network: 'None',
      shortSymbol: '$'
    },
    {
      name: 'Synthetix',
      ticker: 'SNX',
      displayTicker: 'SNX',
      digitalCurrency: true,
      erc20Token: true,
      symbol: '',
      numberOfDecimalPlaces: 18,
      displayDecimalPlaces: 8,
      commonName: 'Synthetix',
      commonTicker: 'SNX',
      network: 'Ethereum',
      shortSymbol: ''
    },
    {
      name: 'sUSDC',
      ticker: 'SUSDC',
      displayTicker: 'Stellar USDC',
      digitalCurrency: true,
      erc20Token: true,
      symbol: '$',
      numberOfDecimalPlaces: 6,
      displayDecimalPlaces: 6,
      commonName: 'USD Coin',
      commonTicker: 'USDC',
      network: 'Stellar',
      shortSymbol: '$'
    },
    {
      name: 'Stablecoin Yield Fund',
      ticker: 'SYF',
      displayTicker: 'SYF',
      digitalCurrency: true,
      erc20Token: true,
      symbol: '',
      numberOfDecimalPlaces: 18,
      displayDecimalPlaces: 6,
      commonName: 'Stablecoin Yield Fund',
      commonTicker: 'SYF',
      network: 'Ethereum',
      shortSymbol: ''
    },
    {
      name: 'Thai Baht',
      ticker: 'THB',
      displayTicker: 'THB',
      digitalCurrency: false,
      erc20Token: false,
      symbol: '฿',
      numberOfDecimalPlaces: 2,
      displayDecimalPlaces: 2,
      commonName: 'Thai Baht',
      commonTicker: 'THB',
      network: 'None',
      shortSymbol: '฿'
    },
    {
      name: 'UMA',
      ticker: 'UMA',
      displayTicker: 'UMA',
      digitalCurrency: true,
      erc20Token: true,
      symbol: '',
      numberOfDecimalPlaces: 18,
      displayDecimalPlaces: 8,
      commonName: 'UMA',
      commonTicker: 'UMA',
      network: 'Ethereum',
      shortSymbol: ''
    },
    {
      name: 'Uniswap',
      ticker: 'UNI',
      displayTicker: 'UNI',
      digitalCurrency: true,
      erc20Token: true,
      symbol: '',
      numberOfDecimalPlaces: 18,
      displayDecimalPlaces: 8,
      commonName: 'Uniswap',
      commonTicker: 'UNI',
      network: 'Ethereum',
      shortSymbol: ''
    },
    {
      name: 'United States Dollar',
      ticker: 'USD',
      displayTicker: 'USD',
      digitalCurrency: false,
      erc20Token: false,
      symbol: '$',
      numberOfDecimalPlaces: 2,
      displayDecimalPlaces: 2,
      commonName: 'United States Dollar',
      commonTicker: 'USD',
      network: 'None',
      shortSymbol: '$'
    },
    {
      name: 'USD Coin',
      ticker: 'USDC',
      displayTicker: 'USDC',
      digitalCurrency: true,
      erc20Token: true,
      symbol: '$',
      numberOfDecimalPlaces: 6,
      displayDecimalPlaces: 6,
      commonName: 'USD Coin',
      commonTicker: 'USDC',
      network: 'Ethereum',
      shortSymbol: '$'
    },
    {
      name: 'Stable USD',
      ticker: 'USDS',
      displayTicker: 'USDS',
      digitalCurrency: true,
      erc20Token: true,
      symbol: '',
      numberOfDecimalPlaces: 6,
      displayDecimalPlaces: 6,
      commonName: 'Stable USD',
      commonTicker: 'USDS',
      network: 'Ethereum',
      shortSymbol: ''
    },
    {
      name: 'Tether',
      ticker: 'USDT',
      displayTicker: 'USDT',
      digitalCurrency: true,
      erc20Token: true,
      symbol: '₮',
      numberOfDecimalPlaces: 6,
      displayDecimalPlaces: 6,
      commonName: 'Tether',
      commonTicker: 'USDT',
      network: 'Ethereum',
      shortSymbol: '₮'
    },
    {
      name: 'Vietnamese Đồng',
      ticker: 'VND',
      displayTicker: 'VND',
      digitalCurrency: false,
      erc20Token: false,
      symbol: '₫',
      numberOfDecimalPlaces: 2,
      displayDecimalPlaces: 2,
      commonName: 'Vietnamese Đồng',
      commonTicker: 'VND',
      network: 'None',
      shortSymbol: '₫'
    },
    {
      name: 'Wrapped Bitcoin',
      ticker: 'WBTC',
      displayTicker: 'WBTC',
      digitalCurrency: true,
      erc20Token: true,
      symbol: '',
      numberOfDecimalPlaces: 8,
      displayDecimalPlaces: 8,
      commonName: 'Wrapped Bitcoin',
      commonTicker: 'WBTC',
      network: 'Ethereum',
      shortSymbol: ''
    },
    {
      name: 'wrapped ethereum',
      ticker: 'WETH',
      displayTicker: 'WETH',
      digitalCurrency: true,
      erc20Token: true,
      symbol: '',
      numberOfDecimalPlaces: 18,
      displayDecimalPlaces: 8,
      commonName: 'Wrapped Ethereum',
      commonTicker: 'WETH',
      network: 'Ethereum',
      shortSymbol: ''
    },
    {
      name: 'Stellar',
      ticker: 'XLM',
      displayTicker: 'XLM',
      digitalCurrency: true,
      erc20Token: false,
      symbol: 'Ξ',
      numberOfDecimalPlaces: 18,
      displayDecimalPlaces: 8,
      commonName: 'Stellar',
      commonTicker: 'XLM',
      network: 'Stellar',
      shortSymbol: 'Ξ'
    },
    {
      name: 'Yearn.finance',
      ticker: 'YFI',
      displayTicker: 'YFI',
      digitalCurrency: true,
      erc20Token: true,
      symbol: '',
      numberOfDecimalPlaces: 18,
      displayDecimalPlaces: 8,
      commonName: 'Yearn.finance',
      commonTicker: 'YFI',
      network: 'Ethereum',
      shortSymbol: ''
    },
    {
      name: 'South African Rand',
      ticker: 'ZAR',
      displayTicker: 'ZAR',
      digitalCurrency: false,
      erc20Token: false,
      symbol: 'R',
      numberOfDecimalPlaces: 2,
      displayDecimalPlaces: 2,
      commonName: 'South African Rand',
      commonTicker: 'ZAR',
      network: 'None',
      shortSymbol: ''
    },
    {
      name: 'ZUSD',
      ticker: 'ZUSD',
      displayTicker: 'ZUSD',
      digitalCurrency: true,
      erc20Token: true,
      symbol: '$',
      numberOfDecimalPlaces: 6,
      displayDecimalPlaces: 6,
      commonName: 'ZUSD',
      commonTicker: 'ZUSD',
      network: 'Ethereum',
      shortSymbol: '$'
    }
  ]
}
